# Generated by Django 3.0.7 on 2020-06-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_doctor_did'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='serial',
        ),
    ]
