# Generated by Django 3.0.7 on 2020-06-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_patient_serial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoinment',
            new_name='Appointment',
        ),
    ]
