# Generated by Django 3.0.7 on 2020-07-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='ammount',
            new_name='amount',
        ),
    ]
